apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storefront
  namespace: argocd
spec:
  source:
    helm:
      valueFiles:
        - ../../gitops/environments/dev/values/storefront.yaml
