#!/usr/bin/env bash
# Pre-edit hook: block edits to generated or vendored files.
#   - build/ and .terraform/ are generated by make targets.
#   - The load balancer controller IAM policy is vendored from upstream; replace the whole
#     file with the new upstream version instead of editing it.
set -euo pipefail

file="$(jq -r '.tool_input.file_path // empty')"

case "$file" in
  */build/* | */.terraform/* | */.tools/*)
    echo "Blocked: $file is generated. Change its source and rerun the make target." >&2
    exit 2
    ;;
  */modules/eks/policies/aws-load-balancer-controller-v*.json)
    echo "Blocked: $file is the vendored upstream policy. Download the new version instead." >&2
    exit 2
    ;;
esac
