apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: catalog-api
  namespace: argocd
spec:
  source:
    helm:
      valueFiles:
        - ../../gitops/environments/prod/values/catalog-api.yaml
